disabled_rules:
- trailing_whitespace

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- Rapid IRC Client/CodeGen
- Rapid IRC ClientTests
- Rapid IRC ClientUITests

identifier_name:
  min_length:
    warning: 3
    error: 1
  excluded:
    - id
    - ui
    - api
    - URL

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 750 # FIXME: aim for 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
#    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 125 # FIXME: aim for 25

reporter: "xcode"
